### ISSUE TITLE
Make a way to request a certain page?

### ISSUE THREAD

**Issue by themerekat** [Symbiota/community-board#10]

**Comment by arbolitoloco** [comment]
Can you elaborate on this, please? Do you mean request a topic to be created in the documentation from within a page in Symbiota?

**Comment by themerekat** [comment]
Yes, sorry for the vagueness; it's still kind of a vague idea in my brain too...basically I'm trying to think of the best way for a user to request a specific documentation page, like "How to use the Exporter tool". Perhaps this is covered in the new templates. It's up for discussion.

**Comment by themerekat** [comment]
@arbolitoloco made a template in symbiota-docs Issues: [Doc-request]
