### ISSUE TITLE
Decide whether Contact Us should be email link or a link to Discussions board in GitHub

### ISSUE THREAD

**Issue by themerekat** [Symbiota/community-board#11]

**Comment by arbolitoloco** [comment]
![Porque no los dos?](https://user-images.githubusercontent.com/17555247/140991967-80b0ba03-bc90-4ee6-aeeb-5189a82f0e00.png)

**Comment by arbolitoloco** [comment]
Closed by 94d13696778e7f7498842c5705d7f346c5716a4c
