### ISSUE TITLE
[Doc Request]: Information about teaching checklists

### ISSUE THREAD

**Issue by themerekat** [Symbiota/community-board#133]
### What tool, feature, or topic are you trying to learn about?

From Mary Barkwoth: Teaching checklists

(Pending more information about this request)

### What kind of tutorial or documentation information would you like to see?

Symbiota Docs

**Comment by themerekat** [comment]
Further clarification:

"The emphasis on them being static checklists, established according to any criteria, for use by teachers and students. It harks back to my experience as a grad student (in the 1970s) in plant anatomy. As a group, we got permission from the prof to make photographic slides of all the demonstration microscope slides in his collection – or perhaps a set he had for teaching. Then we studied them together on our own time and I learned far more from that interaction than from studying them in lab. Did not get as far as liking plant anatomy, but I understood what I was seeing and could relate it to the appropriate structure and function. That is what I see being able to respond with “Adoxaceae” because …. And being told “correct” as adding to the Teaching checklist abilities. Shorter answer; Emphasis on flash card quiz as tools to help students learn to learn. 

On the key tool: yes, I would like a session on that.  Starting from first steps as well as working with an existing resource. Reason: 1) In OpenHerbarium, I have adopted the APG4 families. 2) there is no key to families in the Flora of Pakistan nor in the Flora of Somalia, not even the families that they recognize (basically those of Hutchinson I think). 3) I love dichotomous keys – the joy people have when they first make an id using them is a delight to behold – and I am convinced students learn more from them than using multiaccess keys, but students like multiaccess keys and not everyone cares about the kind of learning that comes from using dichotomous keys; 4) I HATE the time it takes to develop multicaccess keys. Yes, I have started down that path several times."

**Comment by themerekat** [comment]
Consists of:

- Page about the checklist games
- Subheadings on the main Checklists page (https://biokic.github.io/symbiota-docs/user/checklist/) about research checklists versus teaching checklists. How could they be used? What are some examples?

**Comment by arbolitoloco** [comment]
Lindsay's PR #144 partially deals with this.
