### ISSUE TITLE
[Doc Request]: Make a short video about how to fill out the Register as a Publisher form in GBIF

### ISSUE THREAD

**Issue by themerekat** [Symbiota/community-board#142]
### What tool, feature, or topic are you trying to learn about?

How to fill out: https://www.gbif.org/become-a-publisher for those publishing through a Symbiota

### What kind of tutorial or documentation information would you like to see?

Embedded video

**Comment by ljwalker** [comment]
Publishing to GBIF: How to request endorsement as a GBIF publisher: https://youtu.be/ed2VEZCJwEI
