### ISSUE TITLE
[Bug]: Duplication of image tag values

### ISSUE THREAD

**Issue by ljwalker** [Symbiota/community-board#171]
### Contact Details

See osTicket #0001176

### Symbiota portal name

SCAN

### What happened?

When image tag values are selected and saved, the tag values are duplicated in the list. Issue appears to be isolated to SCAN. Submitted by SCAN user: 
> When I need to go in and edit the tags on an image record, I often see the tags duplicated (see screenshot). I don't know why the tags would be duplicated? This happens every time when I log in from home to work in SCAN. It can take 2-3 attempts to save an edit that correctly reflects the changed tag information.

![SCAN Screenshot 2022-06-15 155414 (1)](https://user-images.githubusercontent.com/11181096/174200458-4dd77a4e-80ea-4c81-ad7f-9b5ad49ce701.png)

### What operational systems are you seeing the problem on?

MacOS

### What browsers are you seeing the problem on?

Chrome

**Comment by ljwalker** [comment]
User confirms this error is happening in SCAN when working remotely on Firefox, Chrome, MS Edge, and Safari
![image0](https://user-images.githubusercontent.com/11181096/175943818-6e502e69-207e-4c8a-91a3-1a17322cf244.jpeg).

**Comment by ljwalker** [comment]
Update from user:

> On the initial add of a specimen image, the tag fields are not duplicated. See below


![image1](https://user-images.githubusercontent.com/11181096/175944073-a8dff1c4-4140-4f8f-b78a-8a31e549d746.jpeg)

**Comment by themerekat** [comment]
SCAN is managed by the S2 team. We should forward this on to them, but that's as much as we can do.
