### ISSUE TITLE
[Feature Request]: Ability to associate vocalization files with occurrence records

### ISSUE THREAD

**Issue by rowseydm** [Symbiota/community-board#176]
### Symbiota Portal Name

CSVColl

### Describe the solution you'd like.

It would be fantastic to be able to associate vocalization file types (.wav being the most common) with occurrence records. This originally came up because I have a bat fecal sample that has bat vocalizations associated with it that can be used to identify the species the feces was collected from! How cool would that be to be able to use that as an additional ID reference and data source? But beyond this specific scenario, the ability for individuals to associate vocalizations with voucher specimens or tissue samples would increase the value of both data types, and extends beyond bats to birds, frogs, and I'm guessing even insects.

### When and how would this feature be used? What are some use cases?

Vocalizations are often species specific and can contribute to an observation record or specimen record. These files can be analyzed from the perspectives of comparative behavior, population genetics, or taxonomy. When combined with a voucher, they can be used as proof that the vocalization belongs to the individual or species in question. This makes enabling connections with an occurrence record especially useful.

**Comment by themerekat** [comment]
Neat idea, thanks for sharing!

**Comment by themerekat** [comment]
This is being developed thanks to funding from the Academy of Natural Sciences, Drexel
