### ISSUE TITLE
add geologicalContext terms to public data exports

### ISSUE THREAD

**Issue by ljwalker** [Symbiota/community-board#218]
### Symbiota portal name

Pteridoportal

### What happened?

Fields in the Darwin Core class geologicalContext are not currently exporting when data are downloaded from the public search interface: [native-vs-dwc-output-comparison_2022-10-12.xlsx](https://github.com/BioKIC/symbiota-docs/files/9768030/native-vs-dwc-output-comparison_2022-10-12.xlsx)

### What operational systems are you seeing the problem on?

MacOS

### What browsers are you seeing the problem on?

Chrome

**Comment by themerekat** [comment]
This was probably just never developed

**Comment by ljwalker** [comment]
The following terms **do** export in data backup files from the _Administration Control Panel_:
- eon
- era
- period
- epoch
- earlyInterval
- lateInterval
- absoluteAge
- storageAge
- stage
- localStage
- biota
- biostratigraphy
- taxonEnvironment
- lithogroup _(dwc:group)_
- formation _(dwc:formation)_
- member _(dwc:member)_
- bed _(dwc:bed)_
- lithology
- stratRemarks
- element
- slideProperties
- geologicalContextID _(dwc:geologicalContextID)_
