### ISSUE TITLE
Improve Symbiota Docs search function

### ISSUE THREAD

**Issue by themerekat** [Symbiota/community-board#30]
When searching using a keyword, the search results are listed alphabetically (I think?) rather than in order of relevance. For example, here is the result of searching for the word "permissions"
![image](https://user-images.githubusercontent.com/16688784/144085211-0394ba7d-88da-41b1-aad4-d81617cd83e4.png)

"Permissions" is only a keyword for two pages called User Permissions, but these are listed at the very bottom of the search results (which you have to access by scrolling down in the search results, which is not intuitive to do, since there is no scroll bar).

If there is a way to improve the search function, that would be great. Otherwise, we should at least add a scroll bar to the search results if at all possible.

**Comment by arbolitoloco** [comment]
I changed the search algorithm to use full-text search, plus added a new top level page for searching (b8fa40e23b4c45fe3708a7f642b1eabe53ee6ffe, 2ecf0579d576d30798d4685126e440528d27c2c9, 0a989682d1c97abbba4af873d5d670d0f4076508)
Users can still perform a quick suggestion search in the home page, but pressing "enter" will take them to the search results page. Still need to test new searches with other languages.

**Comment by arbolitoloco** [comment]
499ffaa97659011abd6d2e1243b57c4a48f29c71 fixes spanish support to search
