### ISSUE TITLE
[Bug]: Link to search results not responding

### ISSUE THREAD

**Issue by ljwalker** [Symbiota/community-board#309]
### Symbiota portal name

SEINet, CCH2, Macroalgae

### What happened?

The option to link to search results is not responsive in Chrome or Safari:

![Screenshot 2023-02-13 at 3 53 57 PM](https://user-images.githubusercontent.com/11181096/218601313-6fc90a3b-0759-490a-8d51-fad67d14ca93.png)

### What operational systems are you seeing the problem on?

MacOS

### What browsers are you seeing the problem on?

Chrome

**Comment by themerekat** [comment]
@ljwalker , when you Cmd + V somewhere else after you click this button, does it not paste the URL?
