### ISSUE TITLE
Disallow auto-resizing of images in Symbiota Docs from increasing (and therefore distorting) the image size

### ISSUE THREAD

**Issue by themerekat** [Symbiota/community-board#31]
When an image is very small (like an icon), the auto-resizing makes the image huge and distorted, like so:

![image](https://user-images.githubusercontent.com/16688784/144110529-b940eb5d-9923-41b3-9f7e-90091a3e30a9.png)

@arbolitoloco discussed working on some code that will fix this

**Comment by themerekat** [comment]
@arbolitoloco fixed with commit 6041024

**Comment by arbolitoloco** [comment]
Fixed by 60410247da7edbf8b1a6a947538a7411feec2656
