### ISSUE TITLE
[Doc Request]: Add example csv of loading taxonomic data

### ISSUE THREAD

**Issue by themerekat** [Symbiota/community-board#316]
### What tool, feature, or topic are you trying to learn about?

From Mary Barkworth: "Cat Chapman, ed: Katie Pearson. Batch Loading Taxonomic Data. In: Symbiota Support Hub (2021). Symbiota Documentation. https://biokic.github.io/symbiota-docs/portal_manager/taxonomy/batch_load/. Created on 06 Jul 2022, last edited on 27 Jul 2022. 

Adding a link to a short sample basic csv file would be very helpful."

### What kind of tutorial or documentation information would you like to see?

template CSV file

**Comment by ljwalker** [comment]
Done: https://biokic.github.io/symbiota-docs/portal_manager/taxonomy/batch_load/
