### ISSUE TITLE
[Feature Request]: Ability to view portal-wide statistics on the home page

### ISSUE THREAD

**Issue by themerekat** [Symbiota/community-board#328]
### Is your feature/tool request related to a problem? Please describe.

E.g., how many taxa and/or specimens of certain parent taxa (animals, plants) or regions

### Who else has expressed a desire for this feature/tool?

New Brunswick Biodiversity

**Comment by ljwalker** [comment]
Some related functionality is on the NEON home page: https://biorepo.neonscience.org/portal/index.php

**Comment by themerekat** [comment]
Duplicate of: https://github.com/BioKIC/symbiota-docs/issues/307
