### ISSUE TITLE
Search for records with/without material samples

### ISSUE THREAD

**Issue by themerekat** [Symbiota/community-board#357]
It would be very useful to have a way to identify records with/without material samples in the Collection Management>Edit Occurrence>Record Search Form. A "with material sample" check box, much like the "with images" check box is one idea.

_Originally posted by @ricklevy21 in https://github.com/BioKIC/symbiota-docs/discussions/28#discussioncomment-6091691_

**Comment by themerekat** [comment]
Also requested by UNM

**Comment by ljwalker** [comment]
Also requested by NEON at SSH retreat 2024

**Comment by themerekat** [comment]
This feature has been developed and will be rolled out in Symbiota 3.1
@ricklevy21
