### ISSUE TITLE
[Doc Request]: Documentation for how to enter hosts (into the Associated Taxa field) in MycoPortal

### ISSUE THREAD

**Issue by themerekat** [Symbiota/community-board#36]
### What tool, feature, or topic are you trying to learn about?

Submitted by Jean Lodge

In MycoPortal, you can indicate hosts by entering information in a specific format into the Associated Taxa field. We need instructions on how to do this.

### What kind of tutorial or documentation information would you like to see?

Symbiota Docs page

**Comment by JeanLodge** [comment]
Those like me in Mycology need to communicate what the current and future status is of 'host' in Mycoportal to the broader mycological community. This is especially important for people working with plant (or animal) pathogens, and people working with mycorrhizal fungi and plant endophytes. More ‘documentation’ is needed so Mycoportal users understand the history (Darwin core having a host field and Symbiota not) and then where we are going in the future (adding a host field in Symbiota? Using the formatted text in the field  'host: Xxxx yyyyy’ to extract those data for use? Or populate the new field?

**Comment by themerekat** [comment]
Sent email to Andy Miller requesting more information

**Comment by themerekat** [comment]
From Andy Miller with MycoPortal

Host field has been removed and the Host data have been incorporated into the Associated Taxa field.  Please enter the word “host” followed by a colon, then the host data.  If any Associated Taxa data exists, please use a semicolon to separate Associated Taxa data from Host data.  Please let your transcribers know to use this convention when entering Host data into the Associated Taxa field, for example:  any associated taxa data (if present); host: Quercus alba.

 For example, you previously saw this:

![image](https://user-images.githubusercontent.com/16688784/150002037-ed036fcb-acda-42f5-9471-472d005acd92.png)

You will now see this:

![image](https://user-images.githubusercontent.com/16688784/150002050-41c116f1-cfca-4381-b4cb-ff974c854bfe.png)

**Comment by themerekat** [comment]
Added with 05a48e2
