### ISSUE TITLE
Updated to BioKIC and now missing nav menus

### ISSUE THREAD

**Issue by foozleface** [Symbiota/community-board#42]
### Discussed in https://github.com/BioKIC/symbiota-docs/discussions/41

<div type='discussions-op-text'>

<sup>Originally posted by **foozleface** December 16, 2021</sup>
In the occurrencetabledisplay (accessible via "Edit existing occurrence records" from collections) we noticed that the nav menus vanished. Sad!

  Turns out that the css tag "navpath" is being hidden (display:none, or .hide() ) somewhere. Changing this css tag makes the menu show up, but I'd like to know the underlying intent here; I'm guessing this is configurable someplace. 

  Screen shots show the difference. Note the "1-1000 of 304760 records" which is missing by default in BioKIC.

Any guidance welcome.  

 
![Screen Shot 2021-12-16 at 3 05 58 PM](https://user-images.githubusercontent.com/180338/146462676-9ec8fb62-78e2-4070-83a9-bc8dde72e494.png)
![Screen Shot 2021-12-16 at 3 05 40 PM](https://user-images.githubusercontent.com/180338/146462686-c6861d6e-d022-4850-bbe9-655d54f1a1bd.png)

</div>

**Comment by themerekat** [comment]
Addressed in Discussions
