### ISSUE TITLE
In top menu, make sure Docs section aligns with featured sections on home page

### ISSUE THREAD

**Issue by themerekat** [Symbiota/community-board#5]

**Comment by arbolitoloco** [comment]
Can you please take a screenshot of what do you mean is misaligned? I'm not sure what this means.

**Comment by themerekat** [comment]
Looks better now! But still "Portal Manager Guide" is listed here, even though there is no content for it:
![image](https://user-images.githubusercontent.com/16688784/140996239-d19623e5-1164-4e44-8dac-78e4de224e9e.png)

**Comment by arbolitoloco** [comment]
closed by 1fa88d0f0f9ec0108e46d8725f09dd4b29c39d47
