### ISSUE TITLE
[Feature request] In public search, show pull-down menu for each of multiple taxa listed separated by commas (like in associatedTaxa field)

### ISSUE THREAD

**Issue by themerekat** [Symbiota/community-board#531]
From Mike S:
"First, I have normally separated multiple taxa names with a semicolon, but if you do that, only the first taxon will result in a pull-down menu; the others have to be typed in manually. I discovered that if you separate taxa by a comma instead (space or no space), the pull-down menu appears for all subsequent taxa, a big advantage."

**Comment by themerekat** [comment]
This already exists!

**Comment by MiguelGrande** [comment]
Yes, perhaps it is in some documentation to separate taxa by semi-colons?  If so, consider changing that to commas.

**Comment by themerekat** [comment]
Fixed in the search documentation! https://github.com/BioKIC/symbiota-docs/commit/c9ba7df0ef701aa185d21882f45fc5d8698d8475
