### ISSUE TITLE
[Bug]: Accessing CCH2 is Forbidden 

### ISSUE THREAD

**Issue by tito-abbo** [Symbiota/community-board#549]
### Contact Details

tabbo002@ucr.edu

### Symbiota portal name

CCH2

### What happened?

On multiple browsers, trying to navigate to CCH2, I get the message it is 'forbidden' to visit the site.
![image](https://github.com/BioKIC/symbiota-docs/assets/72320523/47e51226-5521-4744-80de-3d1ae6632559)

**Comment by themerekat** [comment]
Hi @tito-abbo , this is a server rather than a code problem, so I'm removing it from here. We are working on it, though!
