### ISSUE TITLE
[Bug]: User cannot create an account in macroalgae.org

### ISSUE THREAD

**Issue by ljwalker** [Symbiota/community-board#557]
### Contact Details

[See osTicket #0004918](https://help.symbiota.org/scp/tickets.php?id=3968)

### Symbiota portal name

Macroalgae

### What happened?

A user cannot create a new account in the algae portal, and neither the desired username nor their email is already in use in this portal. I have been unable to create a new account for them, even using other email/username combinations.

![image (15)](https://github.com/BioKIC/symbiota-docs/assets/11181096/990e27c5-8711-47d5-9161-29de43811057)

### What operational systems are you seeing the problem on?

MacOS

### What browsers are you seeing the problem on?

Brave

**Comment by themerekat** [comment]
DB permissions were not set correctly, should be fixed!
