### ISSUE TITLE
Merging records doesn't work

### ISSUE THREAD

**Issue by MiguelGrande** [Symbiota/community-board#573]
### Contact Details

msimpson@sdsu.edu

### Symbiota portal name

CCH2

### What happened?

When trying to merge two records, I get this error message
<img width="894" alt="Screenshot 2024-07-21 at 5 16 24 PM" src="https://github.com/user-attachments/assets/856365e5-244c-4708-b8db-dc049895ad0b">
Never had that happened before. Granted, both records had (different) images; not sure if both sets of images can be merged. 

### What operational systems are you seeing the problem on?

MacOS

### What browsers are you seeing the problem on?

Safari

**Comment by themerekat** [comment]
Thanks, Mike! Currently working on this issue.
