### ISSUE TITLE
Wrong format for documentation authors/etc

### ISSUE THREAD

**Issue by arbolitoloco** [Symbiota/community-board#65]
The correct format for including authors, reviewers or translators in the frontmatter of a documentation file is as follows:

```
authors: ["Katie Pearson", "Neil Cobb",  "Ed Gilbert"]
```

I have found many instances of front matters with the wrong format, like so:

```
authors: ["Katie Pearson; Neil Cobb; Ed Gilbert"]
```

As seen, for instance, in `user/checklist/voucher/_index.en.md`.

This affects the correct concatenation of contributors in the citation fragments of the content pages, as well as the index of authors that will be output in a future page.

Please adjust the format as necessary.

**Comment by themerekat** [comment]
Are you seeing this mainly in the user guide? I just checked everything in editor, for example, and all were correctly formatted.

**Comment by themerekat** [comment]
Couldn't find any others besides example described above
