### ISSUE TITLE
For links within pages, direct user to the page in the same language as the original page

### ISSUE THREAD

**Issue by themerekat** [Symbiota/community-board#67]
When you click the link on a page in Symbiota Docs, you will be directed to the English version of the linked page. Is there a way we can change the link to go to, for example, the Spanish page, if the link that the user is following was on a Spanish page?

**Comment by arbolitoloco** [comment]
@themerekat Can you please give me an example of which link you mean in the page? Is the link in the top menu, left menu, page content, footer? What language is the page that contains the link in?

**Comment by themerekat** [comment]
Oh weird, it looks like it's working now!
