### ISSUE TITLE
Translate "Edit this Content on GitHub" button

### ISSUE THREAD

**Issue by themerekat** [Symbiota/community-board#69]
@arbolitoloco  can you point Samanta to where she can translate this? (or you can do it yourself, since you speak Spanish!)
![image](https://user-images.githubusercontent.com/16688784/149998320-278e3103-fba2-4c6f-b2d8-12d9776b6264.png)

**Comment by arbolitoloco** [comment]
@ksorellana, can you please translate the variables in [this file](https://github.com/BioKIC/symbiota-docs/blob/master/i18n/es.yaml)? This will provide translations for the button and also the new search page.

**Comment by arbolitoloco** [comment]
Closed by https://github.com/BioKIC/symbiota-docs/pull/94
