### ISSUE TITLE
[Doc Request]: Datasets and Public Datasets

### ISSUE THREAD

**Issue by arbolitoloco** [Symbiota/community-board#98]
### What tool, feature, or topic are you trying to learn about?

Documentation and tutorial explaining the new developments for datasets:

- How to create a dataset from selected records
- How to add dataset metadata
- How to make a dataset public
- How to find datasets and add a public datasets listing in a portal's menu

### What kind of tutorial or documentation information would you like to see?

Workflow document, tutorial

**Comment by arbolitoloco** [comment]
FYI I'm working on this

**Comment by themerekat** [comment]
Is this done? https://biokic.github.io/symbiota-docs/user/dataset/
Laura, feel free to re-write, add pages, and add your name as desired.
